name: digor_dictionary
description: A new Flutter project.
publish_to: 'none'
version: 2.0.0+8

environment:
  sdk: '^3.6.0 '

dependencies:
  flutter:
    sdk: flutter
  webview_flutter:
  json_annotation: ^4.8.0
  interactive_viewer_2: ^0.0.10
  zoomable_interactive_viewer: ^0.0.5
  flutter_riverpod: ^2.2.0
  styled_text: ^8.1.0
  win32: ^5.13.0
  url_launcher: ^6.1.8
  adaptive_theme: ^3.1.1
  easy_localization: ^3.0.1
  share_plus:
  package_info_plus: ^8.3.0
  flutter_svg: ^2.0.2
  shared_preferences: ^2.0.18
  upgrader: ^11.4.0
  dropdown_button2: ^2.0.0
  just_audio: ^0.10.3
  riverpod_annotation: ^2.0.2
  retrofit: '>=4.0.0 <5.0.0'
  dio: ^5.0.3
  equatable: ^2.0.5
  launch_review_latest: ^1.0.0
  flutter_animate: ^4.1.1+1
  sqflite: ^2.3.0
  path_provider: ^2.1.0
  path: ^1.9.0
  fuzzywuzzy: ^1.2.0
  flutter_inappwebview: ^6.1.5
  vibration: ^3.1.3
  selectable: ^0.5.2
  flutter_widget_from_html: ^0.17.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  json_serializable: ^6.6.1
  riverpod_generator: ^2.1.4
  retrofit_generator: '>=5.0.0 <6.0.0'

flutter:
  uses-material-design: true
  assets:
    - lang/
    - assets/svg_icons/
    - assets/
    - assets/db/exported_digor.db
  fonts:
    - family: Araboto
      fonts:
        - asset: assets/fonts/Araboto/araboto_normal.ttf
          weight: 400
        - asset: assets/fonts/Araboto/araboto_medium.ttf
          weight: 500
        - asset: assets/fonts/Araboto/araboto_light.ttf
          weight: 300
        - asset: assets/fonts/Araboto/araboto_bold.ttf
          weight: 700
        - asset: assets/fonts/Araboto/roboto_italic.ttf
          weight: 400
          style: italic
    - family: BrisaSans
      fonts:
        - asset: assets/fonts/Sans/BrisaSans-Thin.otf
          weight: 100
        - asset: assets/fonts/Sans/BrisaSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/Sans/BrisaSans-Light.otf
          weight: 300
        - asset: assets/fonts/Sans/BrisaSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Sans/BrisaSans-Regular.otf
          weight: 400
        - asset: assets/fonts/Sans/BrisaSans-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/Sans/BrisaSans-Medium.otf
          weight: 500
        - asset: assets/fonts/Sans/BrisaSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Sans/BrisaSans-Bold.otf
          weight: 700
        - asset: assets/fonts/Sans/BrisaSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: SamsungOne
      fonts:
        - asset: assets/fonts/SamsungOne/SamsungOne-500.ttf
        - asset: assets/fonts/SamsungOne/SamsungOne-600.ttf
          weight: 600
        - asset: assets/fonts/SamsungOne/SamsungOne-700.ttf
          weight: 700
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Medium.otf
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Light.otf
          weight: 300
        - asset: assets/fonts/HelveticaNeue/HelveticaNeue-Bold.otf
          weight: 700
